[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  framework = "#static"

# 环境变量说明（需在 Netlify 控制台配置）:
# GITHUB_TOKEN - GitHub Personal Access Token (必需)
# GITHUB_OWNER - GitHub 用户名 (默认: zxt2002721)
# GITHUB_REPO - 仓库名称 (默认: evaluation_adherence_report)
# GITHUB_BRANCH - 分支名称 (默认: main)
# GITHUB_STORAGE_PATH - 存储路径 (默认: questionnaire_data)
